---
# tasks file for nginx

- name: Create certificates directory
  file: 
    path: /etc/ssl/self-signed
    state: directory

- debug:
    msg: |
      System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} and nodename as {{ansible_nodename}}
      The server_name for nginx.conf will be {{inventory_hostname}}.{{ domain_name }}

- name: Generate new self-signed certificate
  command: >
      openssl req -x509 -nodes -subj '/CN={{inventory_hostname}}.{{ domain_name }}' -days 36500
      -newkey rsa:4096 -sha256 -keyout {{ item.key }} -out {{ item.cert }}
      creates={{ item.cert }}
  with_items: "{{ self_signed_certs }}"